---
title: "FAQ"
description: |
  Please send questions directly to Daniel <daniel.himmelstein@gmail.com> and we'll add them here.
output: 
  distill::distill_article:
    toc: true
    toc_float: true
    theme: css/theme-faq.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Can I bring a +1?

If we were aware of a likely +1,
we probably named them in your invite or sent them a separate invite.
If we didn't, you can still list them as part of your party in the RSVP form or ask us separately.
And we will confirm that the additional guest doesn't exceed capacity restrictions.

## Are children allowed?

Yes!
Bring your babies, and we'll teach them Ultimate.

## Are pets allowed?

Unfortunately, the venue doesn't allow pets.
We're sorry but you'll have to leave your furry friends at home.

## Dress

There is no dress code.
But you can help us commemmorate the occaission by wearing creative and colorful attire for the Saturday ceremony and reception.
Dress wild! The more extravagant and ugly the better.

The event will be on grass.
**Do not wear stiletto heels.**
Prefer high-performing footwear or bring a change of shoes, such that your celebrate to your fullest ability.
See [Camping](/camping) for helpful attire for the whole weekend.

## Where do I shower?

There are two solar-bag setups for showering.
The Connecticut River is also quite clean and refreshing at this latitude.
Please note that the facilities are minimal in general.

## How can I help?

We'd love your help in making our wedding special.
Here are some examples of ways you could assist, inspired by actual invitees!

- Can lend my strength for setup
- I'm a licensed airman and can take a drone video
- Can play cello
- Can bring a lawn game called King Kubb
- Have AV skills
- Have a 10kW generator you could borrow (Let us know if you have this!)
- Can make wildflower bouquets

If you'd like to offer a skill or lend an item, let us know in your RSVP or by email.

## Who helped build the website?

Huge thanks to our dear friend, [Silvia Canelón](https://silvia.rbind.io), for creating this beautiful website.
And Trang's sister Ngọc for creating the invitation video.
