---
title: "Results"
description: |
  Results and acknowledgements from the wedding.
output: 
  distill::distill_article:
    toc: true
    toc_float: true
    theme: css/theme-rsvp.css
---

## Race Results

On Sunday, many elite and recreational runners braved the rain and fatigue to run the Off-the-Grid 5k Race.
Course details are available in [the FAQ](/faq.html#running-course).
We are grateful to former Hanover High Cross Country coach, Jim Eakin, for proper timing and setting of the finish line.
Here are the results:

<iframe class="airtable-embed" src="https://airtable.com/embed/shrB7exrpBJmPuMIi?backgroundColor=orange&viewControls=on" frameborder="0" onmousewheel="" width="100%" height="533" style="background: transparent; border: 1px solid #ccc;">
</iframe>

## Volunteers

Thanks everyone who helped make the wedding wonderful.
We very much wanted the event to be a collaborative one that celebrated not just us,
but also the talents of our guests.
A special thank you to the following individuals who played major roles:

- Kurt Wheeler -- Ceremony Officiant
- Daniel Lelchuk -- Cello
- Jim Eakin -- Race Officiant
- Josh Himmelstein -- Ring bearer & airman
- Nadia Penrod -- Yoga Instructor
- Liz Marshall -- Wedding Cake
- Amanda John -- Photographer
- Mathew Griffen & Jordan Hunter: Improv workshop leads
- Brandon Johnson -- Audio/Video Engineer
- Bennett Prescott -- audio advice
- Marissa & Diego Legrand whose 2018 campground wedding was a major insipiration
- Becky Hirschey -- master of logistics

And everyone else who made the wedding possible and helped along the way.

## Vendors

We did have the help of several paid vendors, which we'd like acknowledge:

- Path of Life Garden & [Great River Outfitters](https://www.greatriveroutfitters.com/) for the venue, campground, and river trip.
- [Barefoot Gourmet](https://www.barefoot-gourmet.com/) for reception dinner catering.
- [Blood's catering](https://www.bloodscatering.com/) for the event tent, table, and chair rental.
- [SILO Distillery](https://www.silodistillery.com/silo-distillery) for reception alcohol catering (a Vermont licensed alcohol caterer required by venue / laws).
- [Artisan Eats](https://www.artisaneatsvt.com/) for lunch sandwiches / wraps.
- [Best Septic](https://bestsepticvt.net/) for porta-potty and hand-washing station rental.
- [Home Depot](https://www.homedepot.com/p/rental/Honda-Power-Equipment-2000W-Inverter-Generator-EU2000T1A1-705515/309392156) for the generator rental

## Music

For music, we made several Spotify playlists by occasion:
[Bonfire](https://open.spotify.com/playlist/4Rka7unZ3DvtEMEXQ7YGPo?si=df44ce78a1614cee),
[Romantic background](https://open.spotify.com/playlist/51BmonCD5SAwSgyaJksdW2?si=cb0eb595a3aa479d),
[Prime dance](https://open.spotify.com/playlist/57OX5egKZ50BRHaFl9vzF2?si=8ebfb7b306454f51),
[Late night](https://open.spotify.com/playlist/4KlyFIKSVPQ9pAQrpbSLsS?si=7cb1d7cc1d6a4ab8),
and [Special](https://open.spotify.com/playlist/5XXIW6wodJVN2nKD2zcJYH?si=f967e8cac2094d70).
