---
title: "Schedule"
output: 
  distill::distill_article:
    toc: false
    theme: css/theme-schedule.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

[Add to Calendar](https://calendar.google.com/calendar/u/0?cid=dm5iMWk2aGlsMjJqazljajYxcGZxdTR0ZXNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ)

# Friday, July 23^rd^

| River trip     |                                              |
|:------------------|----------------------------------------------|
| **1:30 pm -- 5:00 pm** | Explore the Connecticut river via kayak, canoe, or paddle board! |

<aside>
The river trip goes ~4 miles down the Connecticut River. The shuttle will leave at 2 pm, so you must be there at 1:30 pm to fill out a waiver and undergo an orientation. Advanced notice (via the RSVP) is required for this activity.
</aside>


| Potluck dinner    |                                                      |
|:------------------|------------------------------------------------------|
| **6:30 pm -- 8:30 pm** | Anything made or purchased with love is appreciated!|

<aside>

If you're able to bring something, great! If you're traveling from afar or unable to bring anything, that is okay.
</aside>

| Socializing       |                                                      |
|:------------------|------------------------------------------------------|
| **8:30 pm -- 11:00 pm** | Beer. Bonfire. Bliss.                                |

------------------------------------------------------------------------

# Saturday, July 24^th^

| MYOB              |                                                      |
|:------------------|------------------------------------------------------|
| **08:00 am -- 11:00 am** | Make your own bed/breakfast/bagel. And coffee.|

| Calibration yoga  |                                                      |
|:------------------|------------------------------------------------------|
| **09:00 am -- 10:00 am** | An alignment-based practice session that transcends boundaries. |

| Unstructured joy  |                                                      |
|:------------------|------------------------------------------------------|
| **11:00 am -- 3:00 pm** | Water activities, yard games, flying discs, sculpture garden tour |

| Unconventional ceremony |                                                |
|:------------------|------------------------------------------------------|
| **4:00 pm -- 5:00 pm** | You don't want to miss this. See [FAQ](faq) for the undress code. |

| Reception         |                                                      |
|:------------------|------------------------------------------------------|
| **5:30 pm -- 8:00 pm** | You especially don't want to miss this. |

| Party      |                                                      |
|:------------------|------------------------------------------------------|
| **8:00 pm -- **      | Dancing with the Driftwood band.                    |


------------------------------------------------------------------------

# Sunday, July 25^th^

| MYOB              |                                                      |
|:------------------|------------------------------------------------------|
| **08:00 am -- 11:00 am** | Good morning. Get yourself ready for the race!       |

| Off-the-grid 5K Run |                                                      |
|:---------------------|------------------------------------------------------|
| **09:00 am -- 10:00 am**  | ~5 km / 3 mile double-loop around the garden. |

<aside>
Grass and dirt track, with slightly uneven footing. Watch your step! We encourage everyone to participate who can, whether you jog or race.
</aside> 

| Award ceremony    |                                                      |
|:------------------|------------------------------------------------------|
| **10:00 am - 11:00 am** | Awards to the top finishers in the male, female, and masters (45+) categories. |

| Lingering festivities |                                                      |
|:-----------------------|---------|
| **11:00 am - 2:00 pm** | Adieu. |
