---
title: "Travel"
description: 
output: 
  distill::distill_article:
    toc: false
    theme: css/theme-travel.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

There will be guest parking at the venue.

If you can't drive / bike to the venue, consider any of the following options:

## Air

- [Boston Logan International Airport](https://www.massport.com/logan-airport/) (BOS),
  with [global service](https://www.flightconnections.com/flights-to-boston-bos).
- [Manchester-Boston Regional Airport](https://www.flymanchester.com/) (MHT).
  [serviced](https://www.flightconnections.com/flights-to-manchester-mht) by American, United, and Southwest.
- [Lebanon Municipal Airport](https://lebanonnh.gov/150/Airport) (LEB),
  serviced by Cape Air with [flights from](https://www.flightconnections.com/flights-from-lebanon-leb) BOS (JetBlue codeshare) and White Plains (HPN).
  There is little convenience to these flights over ground transportation,
  but the small planes do make for a memorable experience.

## Ground

+ Bus: [Dartmouth Coach](https://dartmouthcoach.com/) from Boston or NYC to Lebanon, NH or Hanover, NH
+ Train: [Amtrak](https://www.amtrak.com/) to White River Junction on the [Vermonter Line](https://www.amtrak.com/vermonter-train),
  which is slated to resume service on July 19.

## Carpool

For guests that don't have a car or need a local pick-up,
hopefully we can help coordinate that with other guests.
If you think you will need a ride or might be able to offer a ride,
put your information in [this spreadsheet](https://docs.google.com/spreadsheets/d/1c_IF5f0gY2EpwDWvSkv1FamWb_bG4eqKfgozGD8xTK8/edit).
