---
title: "Thiệp mời"
output: 
  distill::distill_article:
    toc: false
    theme: css/theme-vn.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<center>
<div class="wrapper">
<div class="adjust-line-height-medium">
Ông bà:

<p style="font-size:20px; font-style:italic">
*Lê Đình Lăng*
<br/>
<br/>
*Nguyễn Thị Hà*
</p>
Vũng Tàu, Bà Rịa — Vũng Tàu 
</div>
<div class="adjust-line-height-medium">
Ông bà:

<p style="font-size:20px; font-style:italic">
*Marty Himmelstein*
<br/>
<br/>
*Becky Hirschey*
</p>
Hanover, NH
</div>
</div>

<br>

Trân trọng báo tin **Lễ Thành Hôn** của con chúng tôi:


<div class="adjust-line-height">
<br>
<p style="font-family: 'Mea Culpa'; font-size:35px; font-style:italic">
*Daniel Himmelstein*
</p>

<p style="font-family: 'Mea Culpa'; font-size:35px; font-style:italic">
&
</p>
<p style="font-family: 'Mea Culpa'; font-size:35px; font-style:italic">
*Lê Thảo Trang*
</p>
</div>

<br>
Hôn lễ sẽ được cử hành tại/
The celebration will be at 
<div class="adjust-line-height-small">
<br>
<p style="font-size:24px; font-style:italic">
**Palace Hotel**
</p>
1 Nguyễn Trãi, Phường 1, thành phố Vũng Tàu
<br>
</div>
<br>
vào lúc 18 giờ 30 phút
<div class="adjust-line-height-small">
<br>
**_Thứ Hai, ngày 26 tháng 12 năm 2022_**

**_Monday, December 26, 2022_**

(nhằm ngày 04 tháng 12 năm Nhâm Dần)
</div>
<br>

Sự hiện diện của quý khách là niềm vinh hạnh cho gia đình chúng tôi.

Trân trọng kính mời!

</center>

## For alien visitors

*Welcome!*

We're thrilled that you're coming to visit Trang's beautiful country!
Sincerely!

### Events

You're invited to two official events on Monday, December 26,
both in the peninsular city of Vũng Tàu where one can watch both sunrise and sunset over the ocean.
First is the morning engagement ceremony called Đám Hỏi,
where the groom's family & friends present dowric offerings to the bride's family
(at their residence).
Second is the evening wedding reception at the Palace Hotel.

### Lodging

If you would like to stay at the 4-star [Palace Hotel](https://goo.gl/maps/mbVEmU1ok68hXiRw7),
you can book via Priceline, Booking.com, Expedia, etc.
The nightly rate is around $50 including breakfast.

<aside>
The hotel finds it too logistically challenging to offer any group discount.
</aside>

There are a few AirBnB options but they can be a little further away from city center.

## Travel

The closest airport to Vung Tau is SGN (Saigon / Ho Chi Minh City).
We'll update with information on ground transportation from the airport.

### Hội An

Hội An is a site of world heritage in central Vietnam.
We have booked **group lodging** in a 7 bedroom villa overlooking the rice paddies for anyone who'd like to join.
The villa is reserved from **December 16--21** (Friday--Wednesday).

The villa is in the Cẩm Thanh village and is referred to as "_The An Retreat Hoi An by Đặng Viết Đồng_".
Details can be found on [facebook](https://www.facebook.com/dang.v.dong/posts/pfbid0SUdbBASg7Q63bxxkivRv5VpnbXj5huEPDUUy9Ryu4MjgAmqXE3QsNcSWmgbk43XLl
0) and [airbnb](https://www.airbnb.com/rooms/620873204365705719).
We'll try to acquire world-class amenities:
an occasional private chef and bicycles for all.
The GPS location is `15.88536, 108.35432`
(see on [Google](https://goo.gl/maps/DYeV8MEFa2yFjoWe7) or [OpenStreetMap](https://www.openstreetmap.org/way/286421500)),
which is roughly this address:

> Tống Văn Sương, Hamlet 5  
> Hội An, Quảng Nam 560000, Vietnam

To get to Hội An, fly to Đà Nẵng Airport ([DAD](https://www.flightconnections.com/flights-from-da-nang-dad)).
This will be a cheap domestic flight and is probably easiest to book separately from your flight to Vietnam.

#### Trang & Daniel's itinerary 

We will be in Viet Nam from Nov 27 to Dec 28, 2022.
Let us know when you arrive so Trang can be your guide for a few days!

<aside>
Of course, you're encouraged to stay longer than Dec 28!
</aside>

On the way back to the states, Daniel, Trang, & brother Joshua have booked the following flights
available as a reward booking for 44k United MileagePlus miles & $96.07 per head:

- Wed, Dec 28, 2022.  
  SQ 185 SGN at 7:50 pm to SIN at 10:55 pm
- SQ 308 SIN at 9:00 am to LHR at 3:20 pm
- UA 25 LHR at 5:00 pm to BOS at 7:50 pm

#### Việt Nam visa

Foreign visitors will need a visa.
If your stay does not exceed 30 days and includes only a single entry into Vietnam,
you can get an [e-visa here](https://evisa.xuatnhapcanh.gov.vn/en_US/web/guest/khai-thi-thuc-dien-tu/cap-thi-thuc-dien-tu).
The e-visa process is entirely online, takes ~3 days to process, and costs $25.
We recommend paying with a credit card with no foreign transaction fee. 

For other types of visas, see the [USA Embassy site](https://vietnamembassy-usa.org/consular/visa-application-process) for more information.
We will provide you with the contact details for Trang's father,
should the visa requires a sponsor or destination address.

Please let us know if you have any further questions!

_Reading_:

- [Vietnam International Travel Information (state.gov)](https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/Vietnam.html#/)

- [vietnamembassy-usa.org](https://vietnamembassy-usa.org/consular/visa-application-process)

### Things to do

We're working on a [Viet Nam must-sees Notion page](https://www.notion.so/1d29e420e65047acbb8f0a8c80fc7582) here.
Please let us know if you have any additional questions.

### Monie

1 USD ~= 23,000 VND

The best way to get Viet Nam Dong (VND) is from an ATM, so bring a debit card!
We're not sure how much the Exchange Booths in Viet Nam overcharge you, but we generally avoid them at other airports!

There are [2 ATMs in the arrivals hall](https://www.theworldinmypocket.co.uk/how-not-to-get-scammed-at-saigon-ho-chi-minh-city-airport/) at SGN airport: a _BIDV_ and a _citibank_, facing each other.
If you're taking a taxi from the airport, you can also ask them to stop at an ATM on the way to your destination.
The ATM fee is usually ~3% of the amount you withdraw.

We also recommend bringing some USD cash with you from the US.
You can always go to any bank in Viet Nam to exchange to VND
(no fee, unlike the Exchange Booth).
<!-- # TODO: check with mum on this -->

<aside>
There is no limit but if you're bringing more than $5,000, be sure to declare at customs.
</aside>

_Reading_:

- [ATMs in Ho Chi Minh City | i Tour Vietnam Blogs (itourvn.com)](https://www.itourvn.com/blog/is-it-easy-to-get-money-out-of-atms-in-ho-chi-minh-city)

- [How NOT to get scammed at Saigon Airport (theworldinmypocket.co.uk)](https://www.theworldinmypocket.co.uk/how-not-to-get-scammed-at-saigon-ho-chi-minh-city-airport/)

### Getting to Vung Tau

There are shuttles from the airport every 20 mins or so, unless you arrive at a strange time.
You should see a shuttle lane when you get outside.
Make sure to tell them you're going to [Vung Tau](https://youtu.be/gld41YRCqC0).
Cost is ~$10/person and the shuttle will take you to your exact address.
Depending on traffic, travel time is 2—2.5 hours.
Some popular shuttle companies are: Hoa Mai, Thanh Vinh, Toan Thang, Huy Hoang, and Anh Quoc.


