name: Render and Deploy RMarkdown Website
'on': push
jobs:
  build:
    runs-on: ubuntu-latest
    container: rocker/verse:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages(c('rmarkdown', 'postcards'), repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
      - name: Render Site
        run: |-
          Rscript -e "rmarkdown::render_site(encoding = 'UTF-8')"
          echo "::set-env name=DEPLOY_PATH::$(Rscript -e "cat(rmarkdown::site_config()[['output_dir']])")"
      - name: Deploy
        if: github.ref == 'main' && github.event_name == 'push' && !github.event.repository.fork
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site

