name: Render and Deploy RMarkdown Website
'on':
  push
jobs:
  build:
    runs-on: ubuntu-latest
    container: rocker/verse:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: Install Package Dependencies
        run: |
          Rscript -e "install.packages(c('remotes', 'ragg', 'rmarkdown', 'extrafont', 'distill', 'postcards', 'tidyverse', 'wordcloud', 'tidytext', 'lubridate'), repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "remotes::install_github('gadenbuie/ggpomological')"
      - name: Render Site
        run: |
          Rscript -e "rmarkdown::render_site(encoding = 'UTF-8')"
      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && !github.event.repository.fork
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
