name: Render and Deploy RMarkdown Website
'on':
  push:
  schedule:
    # every day at 5:30 and 17:30 ET
    - cron:  '30 9,21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    container: rocker/verse:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: Install Package Dependencies
        run: |
          wget --directory-prefix=~/.fonts https://fonts.gstatic.com/s/mrdehaviland/v9/OpNVnooIhJj96FdB73296ksbOg3L60P3NilAZTs.woff2
          wget --directory-prefix=~/.fonts https://fonts.googleapis.com/css2?family=Mr+De+Haviland
          fc-cache -rv
          Rscript -e "install.packages(c('remotes', 'rmarkdown', 'distill', 'postcards', 'tidyverse', 'wordcloud', 'tidytext', 'lubridate'), repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "remotes::install_github('gadenbuie/ggpomological')"
      - name: Render Site
        run: |
          Rscript -e "rmarkdown::render_site(encoding = 'UTF-8')"
      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && !github.event.repository.fork
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site

